# Generated by Django 3.2.9 on 2021-11-03 14:16

import corr.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Найменування')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Url')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Короткий зміст кореспонденції',
                'verbose_name_plural': 'Короткий зміст кореспонденції',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='LetterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Найменування')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Url')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тип кореспонденції',
                'verbose_name_plural': 'Тип кореспонденції',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Outсorr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcorr_date', models.DateField(verbose_name='Дата реєстрації')),
                ('outcorr_num', models.CharField(max_length=50, verbose_name='Реєстраційний номер')),
                ('correspondent', models.CharField(max_length=150, verbose_name='Кореспондент')),
                ('letter_scan', models.FileField(blank=True, upload_to=corr.models.outcorr_directory, verbose_name='Скан листа')),
                ('check_scan', models.FileField(blank=True, upload_to=corr.models.check_directory, verbose_name='Скан чека про відправку')),
                ('check_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Сума чека про відправку')),
                ('slug', models.SlugField(unique=True, verbose_name='Url')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Дата внесення змін')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.debtor', verbose_name='Боржник')),
                ('letter_summary', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='corr.lettersummary', verbose_name='Короткий зміст листа')),
                ('letter_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='corr.lettertype', verbose_name='Тип листа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Вихідний лист',
                'verbose_name_plural': 'Вихідна кореспонденція',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Inсorr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incorr_date', models.DateField(verbose_name='Дата реєстрації')),
                ('incorr_num', models.CharField(max_length=50, verbose_name='Реєстраційний номер')),
                ('correspondent', models.CharField(max_length=150, verbose_name='Кореспондент')),
                ('corr_datenum', models.CharField(max_length=50, verbose_name='Дата та номер вхідного листа')),
                ('executed', models.CharField(blank=True, default='-', max_length=50, verbose_name='Відмітка про виконання')),
                ('letter_scan', models.ImageField(blank=True, upload_to=None)),
                ('slug', models.SlugField(unique=True, verbose_name='Url')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Дата внесення змін')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.debtor', verbose_name='Боржник')),
                ('letter_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='corr.lettertype', verbose_name='Тип листа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Вхідний лист',
                'verbose_name_plural': 'Вхідна кореспонденція',
                'ordering': ['-incorr_num'],
            },
        ),
        migrations.CreateModel(
            name='Correspondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(blank=True, max_length=10, verbose_name='Ідентифікаційний код')),
                ('full_name', models.CharField(blank=True, max_length=250, verbose_name='Повне найменування')),
                ('short_name', models.CharField(max_length=150, verbose_name='Скорочене найменування')),
                ('add_country', models.CharField(blank=True, default='Україна', max_length=50, verbose_name='Країна')),
                ('add_index', models.CharField(blank=True, max_length=8, verbose_name='Поштовий індекс')),
                ('add_region', models.CharField(blank=True, max_length=50, verbose_name='Область')),
                ('add_district', models.CharField(blank=True, max_length=50, verbose_name='Район')),
                ('add_city_type', models.CharField(blank=True, choices=[('м.', 'місто'), ('смт.', 'село міського типу'), ('с.', 'село')], default='місто', max_length=20, verbose_name='')),
                ('add_city', models.CharField(blank=True, max_length=50, verbose_name='Населений пункт')),
                ('add_street_type', models.CharField(blank=True, choices=[('бул.', 'бульвар'), ('пр.', 'проспект'), ('вул.', 'вулиця'), ('пров.', 'провулок')], default='вулиця', max_length=20, verbose_name='')),
                ('add_street', models.CharField(blank=True, max_length=50, verbose_name='Назва вулиці')),
                ('add_building', models.CharField(blank=True, default='', max_length=10, verbose_name='Номер будинку')),
                ('add_corps', models.CharField(blank=True, default='', max_length=10, verbose_name='Корпус')),
                ('add_office', models.CharField(blank=True, default='', max_length=10, verbose_name='Офіс')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Дата внесення змін')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Url')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Кореспондент',
                'verbose_name_plural': 'Кореспонденти',
                'ordering': ['short_name'],
            },
        ),
    ]
