# Generated by Django 3.2.9 on 2021-11-05 11:59

import corr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inсorr',
            name='letter_scan',
            field=models.FileField(blank=True, upload_to=corr.models.incorr_directory),
        ),
    ]
