# Generated by Django 3.2.9 on 2021-11-05 12:54

import corr.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corr', '0002_alter_inсorr_letter_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outсorr',
            name='letter_scan',
            field=models.FileField(blank=True, upload_to=corr.models.outcorr_directory, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Скан листа'),
        ),
    ]
