# Generated by Django 3.2.9 on 2021-11-16 16:02

import corr.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corr', '0003_alter_outсorr_letter_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='outсorr',
            name='letter_doc',
            field=models.FileField(blank=True, upload_to=corr.models.outcorr_doc_directory, validators=[django.core.validators.FileExtensionValidator(['docx', 'doc'])], verbose_name='doc листа'),
        ),
        migrations.AlterField(
            model_name='outсorr',
            name='check_scan',
            field=models.FileField(blank=True, upload_to=corr.models.check_directory, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Скан чека про відправку'),
        ),
    ]
