# Generated by Django 3.2.9 on 2021-11-16 16:15

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corr', '0004_auto_20211116_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outсorr',
            name='letter_doc',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/sedak_fs/docx'), upload_to='', validators=[django.core.validators.FileExtensionValidator(['docx', 'doc'])], verbose_name='doc листа'),
        ),
    ]
