# Generated by Django 3.2.9 on 2021-11-03 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=10, verbose_name='Ідентифікаційний код')),
                ('full_name', models.CharField(max_length=250, verbose_name='Повне найменування')),
                ('short_name', models.CharField(max_length=150, verbose_name='Скорочене найменування')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Url')),
                ('case_num', models.CharField(max_length=30, verbose_name='Номер справи про банкрутство')),
                ('nomenclature_num', models.CharField(blank=True, default='', max_length=3, verbose_name='Номенклатурний номер')),
                ('add_country', models.CharField(blank=True, default='Україна', max_length=50, verbose_name='Країна')),
                ('add_index', models.CharField(blank=True, max_length=8, verbose_name='Поштовий індекс')),
                ('add_region', models.CharField(blank=True, max_length=50, verbose_name='Область')),
                ('add_district', models.CharField(blank=True, max_length=50, verbose_name='Район')),
                ('add_city_type', models.CharField(blank=True, choices=[('місто', 'місто'), ('село міського типу', 'село міського типу'), ('село', 'село')], default='місто', max_length=20, verbose_name='')),
                ('add_city', models.CharField(blank=True, max_length=50, verbose_name='Населений пункт')),
                ('add_street_type', models.CharField(blank=True, choices=[('бульвар', 'бульвар'), ('проспект', 'проспект'), ('вулиця', 'вулиця'), ('провулок', 'провулок')], default='вулиця', max_length=20, verbose_name='')),
                ('add_street', models.CharField(blank=True, max_length=50, verbose_name='Назва вулиці')),
                ('add_building', models.CharField(blank=True, default='', max_length=10, verbose_name='Номер будинку')),
                ('add_corps', models.CharField(blank=True, default='', max_length=10, verbose_name='Корпус')),
                ('add_office', models.CharField(blank=True, default='', max_length=10, verbose_name='Офіс')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Дата внесення змін')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Боржник',
                'verbose_name_plural': 'Боржники',
                'ordering': ['-create_time'],
            },
        ),
    ]
